/* include/config.h.  Generated from config.h.in by configure.  */
/*
 *  Configuration header file for compilation of the ALSA driver
 */

/* ALSA section */
/* #undef CONFIG_SND_ISA */
#define CONFIG_SND_SEQUENCER_MODULE 1
#define CONFIG_SND_OSSEMUL 1
#define CONFIG_SND_MIXER_OSS_MODULE 1
#define CONFIG_SND_PCM_OSS_MODULE 1
#define CONFIG_SND_PCM_OSS_PLUGINS 1
#define CONFIG_SND_SEQUENCER_OSS 1
#define CONFIG_SND_SUPPORT_OLD_API 1
#define CONFIG_SND_VERBOSE_PROCFS 1
#define CONFIG_SND_VERBOSE_PRINTK 1
/* #undef CONFIG_SND_DYNAMIC_MINORS */
/* #undef CONFIG_SND_DEBUG */
/* #undef CONFIG_SND_DEBUG_MEMORY */
/* #undef CONFIG_SND_DEBUG_VERBOSE */
/* #undef CONFIG_SND_BIT32_EMUL_MODULE */
/* #undef CONFIG_SND_RTCTIMER_MODULE */
/* #undef CONFIG_SND_HPET_MODULE */
/* #undef CONFIG_SND_SEQ_DUMMY_MODULE */

/* card-dependent section */
/* #undef CONFIG_SND_GENERIC_PM */

/* build section */
#define CONFIG_SND_KERNELDIR "/lib/modules/4.18.0-13-generic/build"
#define CONFIG_ISAPNP_KERNEL 1
#define CONFIG_PNP_KERNEL 1
/* #undef CONFIG_SND_ISAPNP */
/* #undef CONFIG_SND_PNP */

/* 2.4 kernels */
/* #undef CONFIG_HAVE_OLD_REQUEST_MODULE */
#define CONFIG_HAVE_STRLCPY 1
#define CONFIG_HAVE_SNPRINTF 1
#define CONFIG_HAVE_VSNPRINTF 1
#define CONFIG_HAVE_VMALLOC_TO_PAGE 1
/* #undef CONFIG_HAVE_PDE */
#define CONFIG_HAVE_TTY_COUNT_ATOMIC 1
/* #undef CONFIG_HAVE_VIDEO_GET_DRVDATA */
#define CONFIG_HAVE_DUMP_STACK 1
#define CONFIG_HAVE_FFS 1

/* 2.2 kernels */
/* #undef CONFIG_OLD_KILL_FASYNC */
/* #undef CONFIG_HAVE_DMA_ADDR_T */
/* #undef CONFIG_HAVE_MUTEX_MACROS */
#define CONFIG_HAVE_SCNPRINTF 1
#define CONFIG_HAVE_SSCANF 1
#define CONFIG_SND_HAS_BUILTIN_BOOL 1

/* 2.4/2.6 kernels */
#define CONFIG_HAVE_PCI_CONSISTENT_DMA_MASK 1
#define CONFIG_HAVE_KCALLOC 1
#define CONFIG_HAVE_KSTRDUP 1
#define CONFIG_HAVE_KSTRNDUP 1
#define CONFIG_HAVE_KZALLOC 1
#define CONFIG_HAVE_IO_REMAP_PFN_RANGE 1
/* #undef CONFIG_OLD_IO_REMAP_PAGE_RANGE */
#define CONFIG_HAVE_PCI_IOREMAP_BAR 1
/* #undef CONFIG_HAVE_PCI_SAVED_CONFIG */
/* #undef CONFIG_HAVE_NEW_PCI_SAVE_STATE */
#define CONFIG_HAVE_MSLEEP 1
#define CONFIG_HAVE_MSLEEP_INTERRUPTIBLE 1
#define CONFIG_HAVE_MSECS_TO_JIFFIES 1
#define CONFIG_HAVE_PCI_DEV_PRESENT 1
#define CONFIG_SND_HAVE_NEW_IOCTL 1
/* #undef CONFIG_SND_HAVE_CLASS_SIMPLE */
/* #undef CONFIG_CREATE_WORKQUEUE_FLAGS */
#define CONFIG_HAVE_REGISTER_SOUND_SPECIAL_DEVICE 1

/* 2.6 kernel */
/* #undef CONFIG_SND_NESTED_CLASS_DEVICE */
/* #undef CONFIG_SND_OLD_DRIVER_SUSPEND */
/* #undef CONFIG_SND_REMOVE_PAGE_RESERVE */
#define CONFIG_SND_NEW_IRQ_HANDLER 1
#define CONFIG_HAVE_PNP_SUSPEND 1
#define CONFIG_HAVE_GFP_T 1
#define CONFIG_HAVE_INIT_UTSNAME 1
/* #undef CONFIG_SND_HAS_DEVICE_CREATE_DRVDATA */
#define CONFIG_HAVE_IS_POWER_OF_2 1
/* #undef CONFIG_HAVE_DEPRECATED_CONFIG_H */
#define CONFIG_HAVE_GFP_DMA32 1
#define CONFIG_HAVE_PAGE_TO_PFN 1
#define CONFIG_HAVE_VIDEO_DRVDATA 1
#define CONFIG_HAVE_V4L2_CTRLS 1
#define CONFIG_HAVE_GENERATED_AUTOCONF_H 1
#define CONFIG_SND_HAVE_PM_QOS_REQUEST 1
/* #undef CONFIG_SND_HAVE_PM_QOS_REQUEST_STATIC */
/* #undef CONFIG_SND_HAVE_PM_QOS_REQUEST_LIST */
#define CONFIG_SND_HAVE_USB_ALLOC_COHERENT 1
#define CONFIG_HAVE_VZALLOC 1
#define CONFIG_HAVE_DIV_U64 1
#define CONFIG_HAVE_DEV_NAME 1
#define CONFIG_HAVE_DEV_SET_NAME 1
#define CONFIG_HAVE_PUT_PID 1
#define CONFIG_HAVE_PID_VNR 1
/* #undef CONFIG_HAVE_SET_PAGES_ARRAY */

/* 3.x kernel */
/* #undef CONFIG_VM_IOMAP_MEMORY */
